# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpenv-ingress
spec:
  rules:
  - host: localhost
  - http:
      paths:
      - path: /apple
        pathType: Prefix
        backend:
          service:
            name: httpenv-service
            port:
              number: 8080