pipeline {
    agent any
        stages {
            stage ('Greeting') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Confirmation'){
                steps {
                    input('Do you want to proceed?')
                }
            }
            
        stage('Deploying React.js container to Kubernetes') {
            steps {
                dir("FinalProject/k8s") {
                    script {
                    kubernetesDeploy(configs: "agricultor.yaml")
                    }
                }
            }
        }
        }
}