pipeline {
    agent any
        stages {
            stage ('Greeting') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Confirmation'){
                steps {
                    input('Do you want to proceed?')
                }
            }

            stage('Build') {
                steps {
                    dir("FinalProject") {
                        sh "pwd"
                        sh "ls"
                        sh 'kubectl apply -f ./k8s/agricultor.yaml'
                    }
                }
            }
        }
}