pipeline {
  agent any
  stages {
    stage('Checkout Source') {
      steps {
        git 'https://github.com/mahiuinc/IpDC_P2024/FinalProject/k8s'
      }
    }
    stage('Deploying React.js container to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "agricultor.yaml")
        }
      }
    }
  }
}
