pipeline {
    agent any
        stages {
            stage ('Greeting') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Confirmation'){
                steps {
                    input('Do you want to proceed?')
                }
            }

            stage('SonarQube Analysis') {
                            steps {
                                script {
                                    def scannerHome = tool 'SonarQube';
                                    withSonarQubeEnv('SonarQube') {
                                        sh "${scannerHome}/bin/sonar-scanner -f "
                                    }
                                }
                            }
                        }

            stage('Build') {
                steps {
                    dir("Sesion_11/Practica 10") {
                        sh "pwd"
                        sh "ls"
                        sh 'docker-compose up -d --build'
                    }
                }
            }
        }
}