pipeline {
    agent any
        stages {
            stage ('Greeting') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Confirmation'){
                steps {
                    input('Do you want to proceed?')
                }
            }

            stage('Build') {
                steps {
                    sh 'pwd'
                    sh 'docker-compose up -d --build'
                }
            }
        }
}