pipeline {
    agent any
        stages {
            stage ('Greeting') {
                steps {
                    echo 'We are starting this build !!'
                }
            }

            stage ('Confirmation'){
                steps {
                    input('Do you want to proceed?')
                }
            }

            stage('SonarQube Analysis') {
                def scannerHome = tool 'SonarScanner';
                withSonarQubeEnv() {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }

            stage('Build') {
                steps {
                    dir("Sesion_11/Practica 10") {
                        sh "pwd"
                        sh "ls"
                        sh 'docker-compose up -d --build'
                    }
                }
            }
        }
}