version: '3'

services:
  drupal:
    image: drupal:9
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/path/on/host/modules:/var/www/html/modules
      - drupal-profiles:/path/on/host/modules:/var/www/html/profiles
      - drupal-sites:/path/on/host/modules:/var/www/html/sites
      - drupal-themes:/path/on/host/modules:/var/www/html/themes
  psql:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=mahu
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: