pipeline {
    agent any
        stages {
          stage('Deploying nginx service with Kubernetes') {
            steps {
              script {
                kubernetesDeploy(configs: "service.yaml")
              }
            }
    }
  }
}
