# Practica 7
# Miguel Hidalgo

version: '3' #se selecciona la version de docker compose

services: # se especifican los servicios de la solución
  nginx: #Servicio 1 Proxy
    image: nginx:latest # imagen del servicio
    ports: #Puertos externo que se utilizará para el contenedor
      - '8080:80'
    volumes: # Volumenes de información del contenedor
      - ./nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro
    networks: # red(es) a la(s) que pertenecerá el contenedor
      - web_network

  api-server:
    build:
      context: ./api-server #Contexto/directorio donde está el dockerfile para la construcción de la imagen
      dockerfile: api-server.Dockerfile #nombre del dockerfile para crear la imagen
    ports: #Puertos externo que se utilizará para el contenedor
      - '5001:5001'
    networks: # red(es) a la(s) que pertenecerá el contenedor
      - app_network
    volumes:
    #bind-mount con el directorio api-server
      - ./api-server:/app
    # la referencia de node_modules en el contenedor será mi directorio node_modules local. Esto para poder debugear
    # Ojo, si lo quitamos el contenedor termina la ejecución al crearse
      - api-server_node_modules:/app/node_modules
    environment: # variables de entorno, utilizadas para la configuración del contenedor
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}

  redis:
    image: redis:latest # imagen para la creación del contenedor
    networks: # red(es) a la(s) que pertenecerá el contenedor
      - app_network
    volumes:
      - redis_data:/data
    command: redis-server --save 20 1 --loglevel warning
  
  database:
    build:
      context: ./db #Contexto/directorio donde está el dockerfile para la construcción de la imagen
      dockerfile: Dockerfile #nombre del dockerfile para crear la imagen
    volumes: 
      - ./db/init_db.sql:/data/application/init_db.sql
      - db_data:/var/lib/mysql
    networks: # red(es) a la(s) que pertenecerá el contenedor
      - app_network
    command: --init-file /data/application/init_db.sql #comando que se correran una vez el contenedor esté corriendo
    environment: # variables de entorno, utilizadas para la configuración del contenedor
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

  client:
    build:
      context: ./client #Contexto/directorio donde está el dockerfile para la construcción de la imagen
      dockerfile: Dockerfile #nombre del dockerfile para crear la imagen
    networks: # red(es) a la(s) que pertenecerá el contenedor
      - web_network
      - app_network
    volumes:
      - ./client:/app #Bind Mount de contexto app/
      # OJO: de esta manera se descarga node_modules, si lo quitamos ya no la descarga
      - client_node_modules:/app/node_modules
    environment: # variables de entorno, utilizadas para la configuración del contenedor
      - NODE_ENV=development

    
volumes: # Declaración de volumenes
  db_data:
  redis_data:
  api-server_node_modules:
  client_node_modules:

networks: # Creación de nuevas redes
  web_network:
    # Use a custom driver
    driver: bridge
  app_network:
    # Use a custom driver
    driver: bridge